### ISSUE TITLE
Conflict with Better Target

### ISSUE THREAD

**Issue by Merudo** [kandashi/Border-Control#15]
When both [Better Target](https://github.com/sPOiDar/fvtt-module-better-target) and Border-Control are enabled, the following error message is printed to the console:

```
k: Conflict detected between 'better-target' and 'Border-Control'.
Failed to wrap 'Token.prototype._refreshTarget' for 'better-target' with type OVERRIDE. A OVERRIDE wrapper for the same method has already been registered by 'Border-Control'.
    at Function.🎁register [as register] (https://localhost:4004/modules/lib-wrapper/lib-wrapper.js:1:25087)
    at https://localhost:4004/modules/better-target/modules/better_target.js:10:13
    at Function._call (eval at <anonymous> (https://localhost:4004/modules/lib-wrapper/lib-wrapper.js:1:27151), <anonymous>:4:14)
    at Function.callAll (https://localhost:4004/scripts/foundry.js:2456:12)
    at Game.setupGame (https://localhost:4004/scripts/foundry.js:6560:11)
    at async Game._initializeGameView (https://localhost:4004/scripts/foundry.js:7319:5)
    at async Game.initialize (https://localhost:4004/scripts/foundry.js:6471:29)
```

**Comment by kandashi** [comment]
This is known an unavoidable. Simply prioritise better target in lib wrapper to use its targeting system

**Comment by Merudo** [comment]
I still get the following if I prioritize better target:

```
modules/lib-wrapper/lib-wrapper.js:1 libWrapper: Conflict detected between module 'Border-Control' and 'better-target'.
Module 'better-target' has higher priority, and is replacing the OVERRIDE registered by 'Border-Control' for 'Token.prototype._refreshTarget'.
```
I guess there is no avoiding this either.

**Comment by kandashi** [comment]
That is how lib wrapper works yes

**Comment by Merudo** [comment]
Maybe there is a way to forgo the registration of `Token.prototype._refreshTarget` if Better Target is detected?
