### ISSUE TITLE
Bug: Incompatibility with Better Target

### ISSUE THREAD

**Issue by Merudo** [kandashi/Border-Control#34]
When the module `Border Control` is enabled, [Better Target](https://github.com/sPOiDar/fvtt-module-better-target) doesn't work. The following error is generated:

```
VM1519:8 U: Conflict detected between module 'better-target' and module 'Border-Control'.
Failed to wrap 'Token.prototype._refreshTarget' for module 'better-target' with type OVERRIDE. An OVERRIDE wrapper for the same method has already been registered by module 'Border-Control'.
    at Function.🎁register [as register] (https://localhost:3003/modules/lib-wrapper/lib-wrapper.js:1:30123)
    at https://localhost:3003/modules/better-target/modules/better_target.js:10:13
    at Function._call (eval at <anonymous> (https://localhost:3003/modules/lib-wrapper/lib-wrapper.js:1:33400), <anonymous>:4:14)
    at Function.callAll (https://localhost:3003/scripts/foundry.js:153:12)
    at Game.setupGame (https://localhost:3003/scripts/foundry.js:4307:11)
    at async Game._initializeGameView (https://localhost:3003/scripts/foundry.js:5117:5)
    at async Game.initialize (https://localhost:3003/scripts/foundry.js:4202:5)
```

**Comment by Merudo** [comment]
Link to Better Target issue: https://github.com/sPOiDar/fvtt-module-better-target/issues/4

**Comment by kandashi** [comment]
This is a known issue, if you simply place better target above BC in the lib wrapper options that will work as expected (however Better Target is geting depricated afaik)

**Comment by kandashi** [comment]
There is also a setting to disable the target features, which will prevent this
